### PR TITLE
Change print statements into log ones

### PR DESCRIPTION
**Pull request by leoplo**

### CODE REVIEW

**Comment by pedrofran12** [comment]
Hi @leoplo 

Thank you for another PR!

I need to think about this suggestion for a bit...
I agree that the solution to go is to move to logging...
However on my tests I typically send the logs collected by logging to a remote server in order to perform some automation tests (like I only perform a given change in the network when I see that the protocol converged or went to the right state in a given state machine). This means that this "low-level garbage" would also be sent to the remote server and pollute it. Maybe using different log leves for the information would work (INFO/DEBUG)... I need to test this!

**Comment by leoplo** [comment]
Hi @pedrofran12 

My opinion regarding on that matter is : 

- if it is necessary for your tests then it is also probably useful for the user so INFO should be the good log level (tests need to be written requiering as less logs as possible in that case)
- all other "low-level garbage" will then naturally fall in DEBUG level

**Comment by pedrofran12** [comment]
Hi @leoplo 

I have tested your MLD PR with the PIM-DM "stop-daemonizing" PR.

I am not sure about the behavior that I am seeing... maybe it is related with the environment where I am executing (Docker).

I see the terminal spitting all logs when I have the pim-dm process running in the background, including the ones that were original "print" and that were now translated to "logs". Is this expected?
Also when I add interfaces I see "RTNETLINK: no such file or directory". Maybe previously this was being sent to the log file and was a bit hidden from the user. 


Regarding my testing:
- I have started the process with "setsid"
- Added PIM-DM and MLD interfaces
- Saw the terminal spitting logs

**Comment by leoplo** [comment]
Hi @pedrofran12 

It is not about Docker I also see "RTNETLINK: no such file or directory" messages (I believe they come from IPDB). As far as I saw they are not preventing interface addition to work (I also think they were already in logs generated by the current version but I could be mistaken). I am quite sure they come from IPDB (as changing logging format does not have any effect on these messages). It could be related to [kernel configuration](https://stackoverflow.com/questions/4803069/rtnetlink-answers-no-such-file-or-directory) but I will check the logs generated by the current master branch to see if the PR could introduce these messages.

If they were already present then the question would be sould they be hidden from the user.

However I do not believe that these messages could be introduced by this PR but rather by a Pim-dm one if that the case ^^.

**Review by pedrofran12 — APPROVED** [review]

**Pull request merged**
